### ISSUE TITLE
Standalone compilation.

### ISSUE THREAD

**Issue by pvaret** [snaga/monetdb_fdw#2]
Hello,

The Makefile refers to a file called ../../src/Makefile.global, which doesn't exist in this repository. I am led to infer that monetdb_fdw is meant to be compiled as part of the compilation of the entire PostgreSQL. Is that correct? Is there a way to compile it standalone? Thanks.

**Comment by snaga** [comment]
Please see https://github.com/snaga/monetdb_fdw/issues/3 for details.
